# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Learning Snippets
description: >- # this means to ignore newlines until "baseurl:"
  Notes on All Things Tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vivilearns2code.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vivilearns2code
author: vivilearns2code
twitter_username: vivilearns2code
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: vivilearns2code
# Build settings
markdown: kramdown
#theme: minima
minima:
  skin: dark
plugins:
  - jekll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 10  
remote_theme: jekyll/minima
future: false
# set to true to show excerpts on the homepage
show_excerpts: true
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
